// Catálogo base de ingredientes de la casa.
// id: sin acentos ni espacios · cat: agrupa en el panel · staple: se asume siempre en casa
// bean/brand: granos de café, se muestran aparte en la carta.

export const CATEGORIES = [
  { id: 'cafe',       name: 'Café' },
  { id: 'lacteos',    name: 'Lácteos' },
  { id: 'panaderia',  name: 'Panadería' },
  { id: 'proteina',   name: 'Carnes y fiambres' },
  { id: 'verduleria', name: 'Verdulería' },
  { id: 'almacen',    name: 'Almacén' },
  { id: 'condimento', name: 'Condimentos y salsas' },
  { id: 'dulce',      name: 'Dulce' },
  { id: 'congelados', name: 'Congelados y listos' },
  { id: 'snacks',     name: 'Snacks' },
  { id: 'bebidas',    name: 'Bebidas' },
  { id: 'alcohol',    name: 'Alcohol' },
];

export const INGREDIENTS = [
  // ── CAFÉ ─────────────────────────────────────────────
  { id: 'grano-pergamino-navidad',  name: 'Edición Navidad',          cat: 'cafe', bean: true, brand: 'Pergamino' },
  { id: 'grano-san-alberto',        name: 'Arábica Caturra & Castillo', cat: 'cafe', bean: true, brand: 'San Alberto' },
  { id: 'grano-tipica-caturra',     name: 'Caturra',                  cat: 'cafe', bean: true, brand: 'Típica' },
  { id: 'grano-urbania-papayo',     name: 'Papayo',                   cat: 'cafe', bean: true, brand: 'Urbania' },
  { id: 'grano-urbania-tabi',       name: 'Tabi',                     cat: 'cafe', bean: true, brand: 'Urbania' },
  { id: 'grano-urbania-bourbon',    name: 'Bourbon Rosado',           cat: 'cafe', bean: true, brand: 'Urbania' },
  { id: 'grano-urbania-typica',     name: 'Typica',                   cat: 'cafe', bean: true, brand: 'Urbania' },
  { id: 'cafe-molido',              name: 'Café molido / instantáneo', cat: 'cafe' },
  { id: 'cacao',                    name: 'Cacao en polvo',           cat: 'cafe' },
  { id: 'te',                       name: 'Té',                       cat: 'cafe' },
  { id: 'yerba',                    name: 'Yerba mate',               cat: 'cafe' },

  // ── LÁCTEOS ──────────────────────────────────────────
  { id: 'leche',          name: 'Leche',            cat: 'lacteos' },
  { id: 'manteca',        name: 'Manteca',          cat: 'lacteos' },
  { id: 'crema',          name: 'Crema de leche',   cat: 'lacteos' },
  { id: 'yogur',          name: 'Yogur',            cat: 'lacteos' },
  { id: 'queso-cremoso',  name: 'Queso cremoso',    cat: 'lacteos' },
  { id: 'queso-rallado',  name: 'Queso rallado',    cat: 'lacteos' },
  { id: 'mozzarella',     name: 'Mozzarella',       cat: 'lacteos' },
  { id: 'cheddar',        name: 'Cheddar',          cat: 'lacteos' },
  { id: 'gruyere',        name: 'Gruyère',          cat: 'lacteos' },
  { id: 'queso-colonia',  name: 'Queso Colonia',    cat: 'lacteos' },
  { id: 'provolone',      name: 'Provolone',        cat: 'lacteos' },
  { id: 'ricota',         name: 'Ricota',           cat: 'lacteos' },

  // ── PANADERÍA ────────────────────────────────────────
  { id: 'pan',            name: 'Pan',              cat: 'panaderia' },
  { id: 'pan-lactal',     name: 'Pan lactal',       cat: 'panaderia' },
  { id: 'pan-brioche',    name: 'Pan brioche',      cat: 'panaderia' },
  { id: 'tortillas',      name: 'Tortillas / wraps', cat: 'panaderia' },
  { id: 'harina',         name: 'Harina',           cat: 'panaderia' },
  { id: 'polvo-hornear',  name: 'Polvo de hornear', cat: 'panaderia' },
  { id: 'pan-rallado',    name: 'Pan rallado',      cat: 'panaderia' },
  { id: 'levadura',       name: 'Levadura',         cat: 'panaderia' },

  // ── CARNES Y FIAMBRES ────────────────────────────────
  { id: 'huevos',         name: 'Huevos',           cat: 'proteina' },
  { id: 'carne-picada',   name: 'Carne picada',     cat: 'proteina' },
  { id: 'carne-cubos',    name: 'Carne en cubos',   cat: 'proteina' },
  { id: 'bife',           name: 'Bife / churrasco', cat: 'proteina' },
  { id: 'milanesas',      name: 'Milanesas',        cat: 'proteina' },
  { id: 'pollo-pechuga',  name: 'Pechuga de pollo', cat: 'proteina' },
  { id: 'pollo-muslo',    name: 'Muslos de pollo',  cat: 'proteina' },
  { id: 'bondiola',       name: 'Bondiola',         cat: 'proteina' },
  { id: 'lomito',         name: 'Lomito',           cat: 'proteina' },
  { id: 'jamon',          name: 'Jamón',            cat: 'proteina' },
  { id: 'salame',         name: 'Salame',           cat: 'proteina' },
  { id: 'panceta',        name: 'Panceta',          cat: 'proteina' },
  { id: 'chorizo',        name: 'Chorizo',          cat: 'proteina' },
  { id: 'salchichas',     name: 'Salchichas',       cat: 'proteina' },
  { id: 'atun-lata',      name: 'Atún en lata',     cat: 'proteina' },

  // ── VERDULERÍA ───────────────────────────────────────
  { id: 'papa',           name: 'Papa',             cat: 'verduleria' },
  { id: 'batata',         name: 'Batata',           cat: 'verduleria' },
  { id: 'cebolla',        name: 'Cebolla',          cat: 'verduleria' },
  { id: 'cebolla-verdeo', name: 'Cebolla de verdeo', cat: 'verduleria' },
  { id: 'ajo',            name: 'Ajo',              cat: 'verduleria' },
  { id: 'tomate',         name: 'Tomate',           cat: 'verduleria' },
  { id: 'morron',         name: 'Morrón / pimiento', cat: 'verduleria' },
  { id: 'lechuga',        name: 'Lechuga',          cat: 'verduleria' },
  { id: 'rucula',         name: 'Rúcula',           cat: 'verduleria' },
  { id: 'espinaca',       name: 'Espinaca',         cat: 'verduleria' },
  { id: 'palta',          name: 'Palta',            cat: 'verduleria' },
  { id: 'zanahoria',      name: 'Zanahoria',        cat: 'verduleria' },
  { id: 'zapallito',      name: 'Zapallito',        cat: 'verduleria' },
  { id: 'zapallo',        name: 'Zapallo',          cat: 'verduleria' },
  { id: 'brocoli',        name: 'Brócoli',          cat: 'verduleria' },
  { id: 'pepino',         name: 'Pepino',           cat: 'verduleria' },
  { id: 'champignones',   name: 'Champignones',     cat: 'verduleria' },
  { id: 'jengibre',       name: 'Jengibre',         cat: 'verduleria' },
  { id: 'albahaca',       name: 'Albahaca',         cat: 'verduleria' },
  { id: 'perejil',        name: 'Perejil',          cat: 'verduleria' },
  { id: 'limon',          name: 'Limón',            cat: 'verduleria' },
  { id: 'naranja',        name: 'Naranja',          cat: 'verduleria' },
  { id: 'pomelo',         name: 'Pomelo',           cat: 'verduleria' },
  { id: 'banana',         name: 'Banana',           cat: 'verduleria' },
  { id: 'manzana',        name: 'Manzana',          cat: 'verduleria' },
  { id: 'frutilla',       name: 'Frutilla',         cat: 'verduleria' },
  { id: 'fruta-estacion', name: 'Fruta de estación', cat: 'verduleria' },

  // ── ALMACÉN ──────────────────────────────────────────
  { id: 'arroz',              name: 'Arroz',                cat: 'almacen' },
  { id: 'fideos',             name: 'Fideos',               cat: 'almacen' },
  { id: 'fideos-instantaneos', name: 'Fideos instantáneos / ramen', cat: 'almacen' },
  { id: 'polenta',            name: 'Polenta',              cat: 'almacen' },
  { id: 'avena',              name: 'Avena',                cat: 'almacen' },
  { id: 'lentejas',           name: 'Lentejas',             cat: 'almacen' },
  { id: 'garbanzos',          name: 'Garbanzos',            cat: 'almacen' },
  { id: 'porotos',            name: 'Porotos',              cat: 'almacen' },
  { id: 'choclo-lata',        name: 'Choclo en lata',       cat: 'almacen' },
  { id: 'palmitos',           name: 'Palmitos',             cat: 'almacen' },
  { id: 'aceitunas',          name: 'Aceitunas',            cat: 'almacen' },
  { id: 'caldo-cubo',         name: 'Caldo en cubo',        cat: 'almacen' },
  { id: 'leche-coco',         name: 'Leche de coco',        cat: 'almacen' },
  { id: 'nueces',             name: 'Nueces',               cat: 'almacen' },

  // ── CONDIMENTOS Y SALSAS ─────────────────────────────
  { id: 'sal',           name: 'Sal',                cat: 'condimento', staple: true },
  { id: 'pimienta',      name: 'Pimienta',           cat: 'condimento', staple: true },
  { id: 'aceite',        name: 'Aceite',             cat: 'condimento', staple: true },
  { id: 'aceite-oliva',  name: 'Aceite de oliva',    cat: 'condimento' },
  { id: 'vinagre',       name: 'Vinagre',            cat: 'condimento' },
  { id: 'azucar',        name: 'Azúcar',             cat: 'condimento', staple: true },
  { id: 'oregano',       name: 'Orégano',            cat: 'condimento' },
  { id: 'pimenton',      name: 'Pimentón',           cat: 'condimento' },
  { id: 'comino',        name: 'Comino',             cat: 'condimento' },
  { id: 'curry',         name: 'Curry',              cat: 'condimento' },
  { id: 'aji-molido',    name: 'Ají molido',         cat: 'condimento' },
  { id: 'canela',        name: 'Canela',             cat: 'condimento' },
  { id: 'salsa-tomate',  name: 'Salsa de tomate',    cat: 'condimento' },
  { id: 'mayonesa',      name: 'Mayonesa',           cat: 'condimento' },
  { id: 'ketchup',       name: 'Ketchup',            cat: 'condimento' },
  { id: 'mostaza',       name: 'Mostaza',            cat: 'condimento' },
  { id: 'barbacoa',      name: 'Salsa barbacoa',     cat: 'condimento' },
  { id: 'salsa-soja',    name: 'Salsa de soja',      cat: 'condimento' },
  { id: 'sriracha',      name: 'Sriracha / picante', cat: 'condimento' },

  // ── DULCE ────────────────────────────────────────────
  { id: 'dulce-de-leche', name: 'Dulce de leche',   cat: 'dulce' },
  { id: 'mermelada',      name: 'Mermelada',        cat: 'dulce' },
  { id: 'miel',           name: 'Miel',             cat: 'dulce' },
  { id: 'chocolate',      name: 'Chocolate',        cat: 'dulce' },
  { id: 'galletitas',     name: 'Galletitas',       cat: 'dulce' },
  { id: 'alfajores',      name: 'Alfajores',        cat: 'dulce' },
  { id: 'helado',         name: 'Helado',           cat: 'dulce' },

  // ── CONGELADOS Y LISTOS ──────────────────────────────
  { id: 'nuggets',           name: 'Nuggets de pollo',    cat: 'congelados' },
  { id: 'papas-congeladas',  name: 'Papas congeladas',    cat: 'congelados' },
  { id: 'tequenos',          name: 'Tequeños',            cat: 'congelados' },
  { id: 'empanadas',         name: 'Empanadas',           cat: 'congelados' },
  { id: 'tapas-empanada',    name: 'Tapas de empanada',   cat: 'congelados' },

  // ── SNACKS ───────────────────────────────────────────
  { id: 'papas-chip',  name: 'Papas chip',   cat: 'snacks' },
  { id: 'doritos',     name: 'Doritos',      cat: 'snacks' },
  { id: 'mani',        name: 'Maní',         cat: 'snacks' },
  { id: 'palitos',     name: 'Palitos',      cat: 'snacks' },
  { id: 'pochoclo',    name: 'Pochoclo',     cat: 'snacks' },

  // ── BEBIDAS ──────────────────────────────────────────
  { id: 'agua',         name: 'Agua',          cat: 'bebidas', staple: true },
  { id: 'agua-gas',     name: 'Agua con gas',  cat: 'bebidas' },
  { id: 'hielo',        name: 'Hielo',         cat: 'bebidas', staple: true },
  { id: 'coca',         name: 'Coca-Cola',     cat: 'bebidas' },
  { id: 'sprite',       name: 'Sprite',        cat: 'bebidas' },
  { id: 'tonica',       name: 'Tónica',        cat: 'bebidas' },
  { id: 'monster',      name: 'Monster',       cat: 'bebidas' },
  { id: 'jugo-naranja', name: 'Jugo de naranja', cat: 'bebidas' },
  { id: 'jugo-pomelo',  name: 'Jugo de pomelo',  cat: 'bebidas' },

  // ── ALCOHOL ──────────────────────────────────────────
  { id: 'fernet',      name: 'Fernet Branca',  cat: 'alcohol' },
  { id: 'gin',         name: 'Gin',            cat: 'alcohol' },
  { id: 'vodka',       name: 'Vodka',          cat: 'alcohol' },
  { id: 'ron',         name: 'Ron',            cat: 'alcohol' },
  { id: 'whisky',      name: 'Whisky',         cat: 'alcohol' },
  { id: 'jager',       name: 'Jägermeister',   cat: 'alcohol' },
  { id: 'tequila',     name: 'Tequila',        cat: 'alcohol' },
  { id: 'aperol',      name: 'Aperol',         cat: 'alcohol' },
  { id: 'vermut',      name: 'Vermut',         cat: 'alcohol' },
  { id: 'cerveza',     name: 'Cerveza',        cat: 'alcohol' },
  { id: 'vino-tinto',  name: 'Vino tinto',     cat: 'alcohol' },
  { id: 'vino-blanco', name: 'Vino blanco',    cat: 'alcohol' },
  { id: 'espumante',   name: 'Espumante',      cat: 'alcohol' },
];

export const BEANS = INGREDIENTS.filter(i => i.bean).map(i => i.id);
