import { BEANS } from './ingredients.js';

// need: lista de requisitos. Un string = ese ingrediente.
//       Un array = "cualquiera de estos" (ej. manteca O aceite).
// opt:  suma si está, nunca bloquea.
const CAFE = [...BEANS, 'cafe-molido'];

export const SECTIONS = [
  { id: 'cafes',   name: 'Cafés',   label: 'Cafés' },
  { id: 'brunch',  name: 'Brunch',  label: 'Brunch' },
  { id: 'picadas', name: 'Picadas', label: 'Picadas' },
  { id: 'platos',  name: 'Platos',  label: 'Platos' },
  { id: 'tragos',  name: 'Tragos',  label: 'Tragos' },
  { id: 'dulce',   name: 'Dulce',   label: 'Para el dulce' },
];

export const RECIPES = [
  // ══ CAFÉS ═══════════════════════════════════════════
  { id: 'prensa-francesa', name: 'Prensa Francesa', section: 'cafes', tags: ['estrella'], hero: true,
    desc: 'Granos de especialidad · molido grueso · 4 minutos de reposo',
    need: [BEANS, 'agua'], opt: ['azucar', 'leche'] },
  { id: 'cafe-negro', name: 'Café negro', section: 'cafes', tags: ['rapido'],
    desc: 'Café · agua caliente',
    need: [CAFE, 'agua'], opt: ['azucar'] },
  { id: 'latte', name: 'Latte', section: 'cafes', tags: ['suave'],
    desc: 'Café · leche caliente',
    need: [CAFE, 'leche'], opt: ['azucar', 'canela'] },
  { id: 'cortado', name: 'Cortado', section: 'cafes', tags: ['clasico'],
    desc: 'Café · un toque de leche',
    need: [CAFE, 'leche'], opt: ['azucar'] },
  { id: 'capuccino', name: 'Capuccino', section: 'cafes', tags: ['suave'],
    desc: 'Café · leche espumada · cacao por encima',
    need: [CAFE, 'leche', 'cacao'], opt: ['azucar', 'canela'] },
  { id: 'cafe-hielo', name: 'Café con hielo', section: 'cafes', tags: ['rapido'],
    desc: 'Café frío · hielo · leche opcional',
    need: [CAFE, 'hielo'], opt: ['leche', 'azucar'] },
  { id: 'cocoa', name: 'Cocoa', section: 'cafes', tags: ['suave'],
    desc: 'Cacao · leche caliente',
    need: ['cacao', 'leche'], opt: ['azucar', 'canela'] },
  { id: 'submarino', name: 'Submarino', section: 'cafes', tags: ['clasico'],
    desc: 'Leche caliente · barra de chocolate adentro',
    need: ['chocolate', 'leche'] },
  { id: 'te', name: 'Té', section: 'cafes', tags: ['suave'],
    desc: 'Té · agua caliente · limón o miel opcional',
    need: ['te', 'agua'], opt: ['limon', 'miel', 'azucar'] },
  { id: 'mate', name: 'Mate', section: 'cafes', tags: ['clasico'],
    desc: 'Yerba · agua a punto',
    need: ['yerba', 'agua'] },

  // ══ BRUNCH ══════════════════════════════════════════
  { id: 'huevos-revueltos', name: 'Huevos revueltos', section: 'brunch', tags: ['rapido'],
    desc: 'Huevos · manteca · sal · pimienta · crema opcional · tostadas al lado',
    need: ['huevos', ['manteca', 'aceite'], 'sal'], opt: ['crema', 'pimienta', 'pan', 'queso-rallado'] },
  { id: 'huevos-fritos', name: 'Huevos fritos', section: 'brunch', tags: ['rapido'],
    desc: 'Huevos a la sartén · borde crocante · sal gruesa',
    need: ['huevos', 'aceite', 'sal'], opt: ['pan', 'pimienta'] },
  { id: 'huevos-poche', name: 'Huevos poché', section: 'brunch', tags: ['casa'],
    desc: 'Huevos · agua con vinagre · sobre tostada',
    need: ['huevos', 'agua', 'vinagre', 'sal'], opt: ['pan', 'palta', 'pimienta'] },
  { id: 'tostadas-palta', name: 'Tostadas de palta', section: 'brunch', tags: ['veggie'],
    desc: 'Pan tostado · palta · sal · limón · aceite de oliva · opcional: huevo frito o poché',
    need: ['pan', 'palta', 'sal', 'limon'], opt: ['aceite-oliva', 'huevos', 'pimienta', 'tomate'] },
  { id: 'tostadas-manteca', name: 'Tostadas con manteca', section: 'brunch', tags: ['rapido'],
    desc: 'Pan tostado · manteca · sal o azúcar',
    need: [['pan', 'pan-lactal'], 'manteca'], opt: ['azucar', 'mermelada', 'miel'] },
  { id: 'pancakes', name: 'Pancakes', section: 'brunch', tags: ['clasico'],
    desc: 'Harina · huevos · leche · polvo de hornear · manteca · miel o dulce de leche encima',
    need: ['harina', 'huevos', 'leche', 'polvo-hornear'], opt: ['manteca', 'miel', 'dulce-de-leche', 'banana', 'azucar'] },
  { id: 'quesadillas', name: 'Quesadillas', section: 'brunch', tags: ['casa'],
    desc: 'Tortillas · queso · relleno a elección · salsa · crema · en sartén hasta dorar',
    need: ['tortillas', ['queso-cremoso', 'cheddar', 'mozzarella']], opt: ['pollo-pechuga', 'carne-picada', 'salsa-tomate', 'crema', 'cebolla', 'morron'] },
  { id: 'tostado', name: 'Tostado de jamón y queso', section: 'brunch', tags: ['rapido'],
    desc: 'Pan lactal · jamón · queso · a la plancha',
    need: [['pan-lactal', 'pan'], 'jamon', ['queso-cremoso', 'mozzarella', 'cheddar']], opt: ['manteca', 'tomate', 'oregano'] },
  { id: 'omelette', name: 'Omelette simple', section: 'brunch', tags: ['rapido'],
    desc: 'Huevos batidos · lo que haya en la heladera adentro',
    need: ['huevos', 'sal', ['manteca', 'aceite']], opt: ['queso-cremoso', 'jamon', 'cebolla', 'tomate', 'morron', 'espinaca', 'champignones'] },
  { id: 'tortilla-papa', name: 'Tortilla de papa', section: 'brunch', tags: ['clasico'],
    desc: 'Papa · huevos · cebolla · a la sartén, jugosa por dentro',
    need: ['papa', 'huevos', 'cebolla', 'aceite', 'sal'], opt: ['perejil', 'queso-rallado', 'pimienta'] },
  { id: 'avena-leche', name: 'Avena con leche', section: 'brunch', tags: ['suave'],
    desc: 'Avena · leche caliente · fruta y miel encima',
    need: ['avena', 'leche'], opt: ['banana', 'miel', 'canela', 'nueces', 'manzana'] },
  { id: 'yogur-fruta', name: 'Yogur con fruta', section: 'brunch', tags: ['veggie'],
    desc: 'Yogur · fruta fresca · avena o nueces por encima',
    need: ['yogur', ['fruta-estacion', 'banana', 'frutilla', 'manzana']], opt: ['avena', 'miel', 'nueces', 'mermelada'] },
  { id: 'licuado-banana', name: 'Licuado de banana', section: 'brunch', tags: ['rapido'],
    desc: 'Banana · leche · hielo · miel opcional',
    need: ['banana', 'leche'], opt: ['hielo', 'miel', 'avena', 'cacao'] },
  { id: 'medialuna-plancha', name: 'Pan a la plancha con queso', section: 'brunch', tags: ['rapido'],
    desc: 'Pan abierto · queso derretido · orégano',
    need: [['pan', 'pan-lactal'], ['mozzarella', 'queso-cremoso']], opt: ['oregano', 'tomate', 'aceite-oliva'] },

  // ══ PICADAS ═════════════════════════════════════════
  { id: 'fritas-casa', name: 'Fritas de la casa', section: 'picadas', tags: ['picante'],
    desc: 'Papas corte fino · especiadas · picantes',
    need: [['papa', 'papas-congeladas'], 'aceite', 'sal'], opt: ['pimenton', 'aji-molido', 'ajo', 'mayonesa'] },
  { id: 'papas-cheddar', name: 'Papas con cheddar', section: 'picadas', tags: ['estrella'],
    desc: 'Papas · cheddar fundido · panceta opcional',
    need: [['papa', 'papas-congeladas'], 'cheddar', 'aceite'], opt: ['panceta', 'cebolla-verdeo', 'sriracha'] },
  { id: 'nuggets', name: 'Nuggets de pollo', section: 'picadas', tags: ['casa'],
    desc: 'Nuggets de pollo · mayonesa · barbacoa · mostaza',
    need: ['nuggets'], opt: ['mayonesa', 'barbacoa', 'mostaza', 'ketchup'] },
  { id: 'fiambres-quesos', name: 'Fiambres y quesos', section: 'picadas', tags: ['clasico'],
    desc: 'Bondiola · lomito · gruyère · colonia · aceitunas',
    need: [['bondiola', 'lomito', 'jamon', 'salame'], ['gruyere', 'queso-colonia', 'queso-cremoso']], opt: ['aceitunas', 'pan', 'nueces', 'mani'] },
  { id: 'porquerias', name: 'Porquerías random', section: 'picadas', tags: ['rapido'],
    desc: 'Papas chip · maní · Doritos',
    need: [['papas-chip', 'mani', 'doritos', 'palitos', 'pochoclo']] },
  { id: 'provolone', name: 'Provolone', section: 'picadas', tags: ['estrella'],
    desc: 'Queso provolone a la plancha',
    need: ['provolone'], opt: ['oregano', 'aceite-oliva', 'aji-molido', 'pan'] },
  { id: 'tequenos', name: 'Tequeños', section: 'picadas', tags: ['estrella'],
    desc: 'Palitos de masa frita rellenos de queso',
    need: ['tequenos'], opt: ['salsa-tomate', 'mayonesa'] },
  { id: 'bruschetta', name: 'Bruschetta', section: 'picadas', tags: ['veggie'],
    desc: 'Pan tostado · tomate · ajo · aceite de oliva · albahaca',
    need: ['pan', 'tomate', 'ajo', 'aceite-oliva', 'sal'], opt: ['albahaca', 'oregano', 'mozzarella'] },
  { id: 'guacamole', name: 'Guacamole', section: 'picadas', tags: ['veggie'],
    desc: 'Palta · limón · cebolla · sal · con Doritos al lado',
    need: ['palta', 'limon', 'cebolla', 'sal'], opt: ['tomate', 'doritos', 'perejil', 'sriracha'] },
  { id: 'aceitunas-queso', name: 'Aceitunas y queso', section: 'picadas', tags: ['rapido'],
    desc: 'Aceitunas · queso en cubos · aceite de oliva',
    need: ['aceitunas', ['queso-cremoso', 'gruyere', 'queso-colonia']], opt: ['aceite-oliva', 'oregano'] },
  { id: 'empanadas-listas', name: 'Empanadas', section: 'picadas', tags: ['casa'],
    desc: 'Al horno hasta dorar · limón al lado',
    need: ['empanadas'], opt: ['limon', 'sriracha'] },
  { id: 'pochoclo-casero', name: 'Pochoclo', section: 'picadas', tags: ['rapido'],
    desc: 'Pochoclo · sal o azúcar',
    need: ['pochoclo'], opt: ['sal', 'azucar', 'manteca'] },

  // ══ PLATOS ══════════════════════════════════════════
  { id: 'omelette-huerta', name: 'Omelette de la huerta', section: 'platos', tags: ['veggie'],
    desc: 'Huevos · pimiento · cebolla · tomate · queso · sal · pimienta · aceite de oliva',
    need: ['huevos', 'morron', 'cebolla', 'tomate', ['queso-cremoso', 'mozzarella'], 'sal'], opt: ['aceite-oliva', 'pimienta', 'espinaca'] },
  { id: 'la-burger', name: 'La Burger', section: 'platos', tags: ['estrella'],
    desc: 'Pan brioche · medallón de carne · cheddar · lechuga · tomate · cebolla caramelizada · mayonesa',
    need: ['pan-brioche', 'carne-picada', 'cheddar', 'lechuga', 'tomate', 'cebolla', 'mayonesa'], opt: ['ketchup', 'mostaza', 'panceta', 'papas-congeladas'] },
  { id: 'burger-simple', name: 'Burger simple', section: 'platos', tags: ['rapido'],
    desc: 'Pan · medallón · sal y pimienta · lo que haya arriba',
    need: [['pan-brioche', 'pan-lactal', 'pan'], 'carne-picada', 'sal'], opt: ['cheddar', 'lechuga', 'tomate', 'cebolla', 'mayonesa', 'ketchup'] },
  { id: 'pollo-pure', name: 'Pollo a la plancha & puré', section: 'platos', tags: ['clasico'],
    desc: 'Churrasco de pechuga a la plancha · puré de papa mantecoso',
    need: ['pollo-pechuga', 'papa', 'manteca', 'sal'], opt: ['leche', 'pimienta', 'limon', 'ajo', 'perejil'] },
  { id: 'ramen-medianoche', name: 'Ramen de medianoche', section: 'platos', tags: ['picante'],
    desc: 'Ramen instantáneo · caldo picante · toppings a elección',
    need: ['fideos-instantaneos', 'agua'], opt: ['huevos', 'sriracha', 'cebolla-verdeo', 'salsa-soja', 'champignones', 'panceta'] },
  { id: 'saltado-carne', name: 'Saltado de carne', section: 'platos', tags: ['casa'],
    desc: 'Carne en cubos · morrón · cebolla · ajo · especias · salteado en sartén',
    need: ['carne-cubos', 'morron', 'cebolla', 'ajo', 'aceite', 'sal'], opt: ['salsa-soja', 'arroz', 'comino', 'perejil', 'papas-congeladas'] },
  { id: 'milanesas', name: 'Milanesas', section: 'platos', tags: ['clasico'],
    desc: 'Milanesas doradas · limón · guarnición a elección',
    need: ['milanesas', 'aceite'], opt: ['limon', 'papa', 'lechuga', 'tomate', 'arroz'] },
  { id: 'milanesas-caseras', name: 'Milanesas caseras', section: 'platos', tags: ['casa'],
    desc: 'Carne o pollo · huevo batido · pan rallado · a la sartén o al horno',
    need: [['bife', 'pollo-pechuga', 'carne-cubos'], 'pan-rallado', 'huevos', 'aceite', 'sal'], opt: ['ajo', 'perejil', 'queso-rallado', 'limon', 'papa'] },
  { id: 'mila-napolitana', name: 'Milanesa napolitana', section: 'platos', tags: ['estrella'],
    desc: 'Milanesa · salsa de tomate · mozzarella gratinada · orégano',
    need: ['milanesas', 'salsa-tomate', 'mozzarella', 'aceite'], opt: ['oregano', 'jamon', 'papas-congeladas'] },
  { id: 'fideos-salsa', name: 'Fideos con salsa', section: 'platos', tags: ['clasico'],
    desc: 'Fideos al dente · salsa de tomate · queso rallado',
    need: ['fideos', 'salsa-tomate', 'sal'], opt: ['queso-rallado', 'albahaca', 'ajo', 'aceite-oliva', 'carne-picada'] },
  { id: 'fideos-manteca', name: 'Fideos con manteca', section: 'platos', tags: ['rapido'],
    desc: 'Fideos · manteca · queso rallado · pimienta',
    need: ['fideos', 'manteca', 'sal'], opt: ['queso-rallado', 'pimienta', 'albahaca'] },
  { id: 'carbonara', name: 'Carbonara express', section: 'platos', tags: ['estrella'],
    desc: 'Fideos · huevo · panceta · queso · mucha pimienta',
    need: ['fideos', 'huevos', 'panceta', 'queso-rallado', 'sal'], opt: ['pimienta', 'ajo'] },
  { id: 'bolognesa', name: 'Fideos a la bolognesa', section: 'platos', tags: ['casa'],
    desc: 'Carne picada · salsa · cebolla y ajo · fideos',
    need: ['fideos', 'carne-picada', 'salsa-tomate', 'cebolla', 'ajo', 'aceite', 'sal'], opt: ['queso-rallado', 'oregano', 'morron', 'zanahoria'] },
  { id: 'arroz-pollo', name: 'Arroz con pollo', section: 'platos', tags: ['casa'],
    desc: 'Arroz · pollo · cebolla y ajo · caldo',
    need: ['arroz', ['pollo-pechuga', 'pollo-muslo'], 'cebolla', 'ajo', 'aceite', 'sal'], opt: ['morron', 'caldo-cubo', 'choclo-lata', 'curry', 'perejil'] },
  { id: 'arroz-blanco', name: 'Arroz blanco', section: 'platos', tags: ['rapido'],
    desc: 'Arroz suelto · sal · manteca opcional',
    need: ['arroz', 'agua', 'sal'], opt: ['manteca', 'salsa-soja', 'huevos'] },
  { id: 'pollo-horno', name: 'Pollo al horno con papas', section: 'platos', tags: ['clasico'],
    desc: 'Pollo · papas · limón · orégano · al horno',
    need: [['pollo-pechuga', 'pollo-muslo'], 'papa', 'aceite', 'sal'], opt: ['limon', 'oregano', 'ajo', 'cebolla', 'pimenton'] },
  { id: 'bife-ensalada', name: 'Bife con ensalada', section: 'platos', tags: ['clasico'],
    desc: 'Churrasco a la plancha · ensalada fresca al lado',
    need: ['bife', 'sal', 'lechuga', 'tomate'], opt: ['aceite-oliva', 'vinagre', 'cebolla', 'pimienta', 'papa'] },
  { id: 'ensalada-completa', name: 'Ensalada completa', section: 'platos', tags: ['veggie'],
    desc: 'Verde · tomate · lo que haya · aceite de oliva y sal',
    need: ['lechuga', 'tomate', 'aceite-oliva', 'sal'], opt: ['zanahoria', 'pepino', 'huevos', 'atun-lata', 'aceitunas', 'choclo-lata', 'palmitos', 'rucula', 'vinagre'] },
  { id: 'ensalada-atun', name: 'Ensalada de atún', section: 'platos', tags: ['rapido'],
    desc: 'Atún · verde · tomate · aceite de oliva',
    need: ['atun-lata', 'lechuga', 'tomate', 'aceite-oliva', 'sal'], opt: ['choclo-lata', 'cebolla', 'huevos', 'mayonesa', 'aceitunas'] },
  { id: 'wrap-pollo', name: 'Wrap de pollo', section: 'platos', tags: ['rapido'],
    desc: 'Tortilla · pollo · verde · mayonesa',
    need: ['tortillas', 'pollo-pechuga', 'lechuga', 'mayonesa'], opt: ['tomate', 'cheddar', 'palta', 'cebolla', 'sriracha'] },
  { id: 'sopa-verduras', name: 'Sopa de verduras', section: 'platos', tags: ['veggie'],
    desc: 'Zapallo o zanahoria · cebolla · caldo · cremosa',
    need: [['zapallo', 'zanahoria', 'papa'], 'cebolla', 'caldo-cubo', 'agua', 'sal'], opt: ['crema', 'ajo', 'aceite-oliva', 'pan'] },
  { id: 'guiso-lentejas', name: 'Guiso de lentejas', section: 'platos', tags: ['casa'],
    desc: 'Lentejas o porotos · sofrito · chorizo opcional · a fuego lento',
    need: [['lentejas', 'porotos'], 'cebolla', 'morron', 'ajo', 'aceite', 'sal'], opt: ['chorizo', 'papa', 'zanahoria', 'caldo-cubo', 'pimenton', 'panceta'] },
  { id: 'pure-papa', name: 'Puré de papa', section: 'platos', tags: ['suave'],
    desc: 'Papa · manteca · leche · nuez moscada opcional',
    need: ['papa', 'manteca', 'sal'], opt: ['leche', 'queso-rallado', 'pimienta'] },
  { id: 'papas-horno', name: 'Papas al horno', section: 'platos', tags: ['veggie'],
    desc: 'Papas o batatas en gajos · aceite · especias · al horno',
    need: [['papa', 'batata'], 'aceite', 'sal'], opt: ['oregano', 'ajo', 'pimenton', 'perejil', 'aji-molido'] },
  { id: 'salteado-verduras', name: 'Salteado de verduras', section: 'platos', tags: ['veggie'],
    desc: 'Verduras al wok · ajo · salsa de soja',
    need: [['brocoli', 'zapallito', 'zanahoria', 'morron', 'champignones'], 'cebolla', 'ajo', 'aceite'], opt: ['salsa-soja', 'jengibre', 'arroz', 'sriracha', 'huevos'] },
  { id: 'pizza-casera', name: 'Pizza casera', section: 'platos', tags: ['estrella'],
    desc: 'Masa de la casa · salsa · mozzarella · orégano',
    need: ['harina', 'salsa-tomate', 'mozzarella', 'aceite-oliva', 'sal'], opt: ['levadura', 'oregano', 'aceitunas', 'jamon', 'morron', 'albahaca'] },
  { id: 'choripan', name: 'Choripán', section: 'platos', tags: ['casa'],
    desc: 'Chorizo a la plancha · pan crocante',
    need: ['chorizo', 'pan'], opt: ['perejil', 'ajo', 'aceite-oliva', 'aji-molido'] },
  { id: 'panchos', name: 'Panchos', section: 'platos', tags: ['rapido'],
    desc: 'Salchichas · pan · ketchup, mostaza y mayonesa',
    need: ['salchichas', ['pan', 'pan-lactal']], opt: ['ketchup', 'mostaza', 'mayonesa', 'papas-chip', 'queso-rallado'] },
  { id: 'polenta-queso', name: 'Polenta con queso', section: 'platos', tags: ['suave'],
    desc: 'Polenta cremosa · manteca · queso rallado',
    need: ['polenta', 'agua', 'sal'], opt: ['queso-rallado', 'manteca', 'salsa-tomate', 'leche'] },
  { id: 'risotto-champis', name: 'Risotto de champignones', section: 'platos', tags: ['estrella'],
    desc: 'Arroz cremoso · champignones · queso · manteca',
    need: ['arroz', 'champignones', 'cebolla', 'manteca', 'caldo-cubo', 'sal'], opt: ['queso-rallado', 'vino-blanco', 'ajo', 'perejil'] },
  { id: 'tarta-verdura', name: 'Tarta de verdura', section: 'platos', tags: ['veggie'],
    desc: 'Espinaca · huevo · queso · sobre masa',
    need: ['espinaca', 'huevos', ['queso-cremoso', 'queso-rallado', 'mozzarella'], 'cebolla', 'sal'], opt: ['ricota', 'crema', 'harina', 'tapas-empanada'] },
  { id: 'garbanzos-curry', name: 'Garbanzos al curry', section: 'platos', tags: ['veggie'],
    desc: 'Garbanzos · curry · leche de coco · arroz al lado',
    need: ['garbanzos', 'curry', 'cebolla', 'ajo', 'aceite', 'sal'], opt: ['leche-coco', 'arroz', 'tomate', 'jengibre', 'espinaca'] },
  { id: 'huevos-revueltos-cena', name: 'Revuelto de verduras', section: 'platos', tags: ['rapido'],
    desc: 'Huevos revueltos con lo que quede en la heladera',
    need: ['huevos', ['zapallito', 'espinaca', 'champignones', 'morron', 'cebolla'], 'aceite', 'sal'], opt: ['queso-rallado', 'jamon', 'pimienta'] },

  // ══ TRAGOS ══════════════════════════════════════════
  { id: 'fernet-coca', name: 'Fernet con Coca', section: 'tragos', tags: ['clasico'],
    desc: 'Fernet Branca · Coca-Cola · hielo · limón',
    need: ['fernet', 'coca', 'hielo'], opt: ['limon'] },
  { id: 'gin-tonic', name: 'Gin tonic', section: 'tragos', tags: ['clasico'],
    desc: 'Gin · tónica · hielo · limón · pimienta o romero opcional',
    need: ['gin', 'tonica', 'hielo'], opt: ['limon', 'pimienta', 'pepino', 'naranja'] },
  { id: 'gin-pomelo', name: 'Gin pomelo', section: 'tragos', tags: ['casa'],
    desc: 'Gin · pomelo · hielo · tónica encima',
    need: ['gin', ['pomelo', 'jugo-pomelo'], 'hielo'], opt: ['tonica', 'azucar'] },
  { id: 'vodka-pomelo', name: 'Vodka pomelo', section: 'tragos', tags: ['rapido'],
    desc: 'Vodka · jugo de pomelo · hielo',
    need: ['vodka', ['pomelo', 'jugo-pomelo'], 'hielo'] },
  { id: 'vodka-naranja', name: 'Vodka naranja', section: 'tragos', tags: ['rapido'],
    desc: 'Vodka · jugo de naranja · hielo',
    need: ['vodka', ['naranja', 'jugo-naranja'], 'hielo'] },
  { id: 'jager-monster', name: 'Jäger con Monster', section: 'tragos', tags: ['estrella'],
    desc: 'Jägermeister · Monster Energy · hielo',
    need: ['jager', 'monster', 'hielo'] },
  { id: 'cuba-libre', name: 'Cuba libre', section: 'tragos', tags: ['clasico'],
    desc: 'Ron · Coca-Cola · hielo · limón',
    need: ['ron', 'coca', 'hielo'], opt: ['limon'] },
  { id: 'aperol-spritz', name: 'Aperol Spritz', section: 'tragos', tags: ['estrella'],
    desc: 'Aperol · espumante · soda · naranja',
    need: ['aperol', 'espumante', 'hielo'], opt: ['agua-gas', 'naranja'] },
  { id: 'vermut-tonica', name: 'Vermut con tónica', section: 'tragos', tags: ['clasico'],
    desc: 'Vermut · tónica · hielo · naranja',
    need: ['vermut', 'tonica', 'hielo'], opt: ['naranja', 'aceitunas'] },
  { id: 'whisky-rocas', name: 'Whisky on the rocks', section: 'tragos', tags: ['suave'],
    desc: 'Whisky · hielo · nada más',
    need: ['whisky', 'hielo'] },
  { id: 'tequila-shot', name: 'Tequila', section: 'tragos', tags: ['picante'],
    desc: 'Shot · sal · limón',
    need: ['tequila'], opt: ['limon', 'sal'] },
  { id: 'cerveza', name: 'Cerveza', section: 'tragos', tags: ['casa'],
    desc: 'Bien fría · preguntar variedad a Dan',
    need: ['cerveza'] },
  { id: 'vino', name: 'Vino', section: 'tragos', tags: ['clasico'],
    desc: 'Copa de tinto o blanco de la casa',
    need: [['vino-tinto', 'vino-blanco']] },
  { id: 'limonada', name: 'Limonada', section: 'tragos', tags: ['veggie'],
    desc: 'Limón exprimido · agua · azúcar · hielo · jengibre o albahaca',
    need: ['limon', 'agua', 'azucar', 'hielo'], opt: ['jengibre', 'albahaca', 'agua-gas'] },
  { id: 'jugo-exprimido', name: 'Jugo exprimido', section: 'tragos', tags: ['veggie'],
    desc: 'Naranja o pomelo recién exprimido',
    need: [['naranja', 'pomelo']], opt: ['hielo', 'azucar'] },
  { id: 'agua-sin-gas', name: 'Agua sin gas', section: 'tragos', tags: ['suave'],
    desc: 'Agua fría sin gas',
    need: ['agua'], opt: ['hielo', 'limon'] },
  { id: 'gaseosa', name: 'Gaseosa', section: 'tragos', tags: ['rapido'],
    desc: 'Coca o Sprite con hielo',
    need: [['coca', 'sprite']], opt: ['hielo', 'limon'] },

  // ══ DULCE ═══════════════════════════════════════════
  { id: 'pancakes-ddl', name: 'Pancakes con dulce de leche', section: 'dulce', tags: ['estrella'],
    desc: 'Pancakes · dulce de leche · opcional: banana o crema',
    need: ['harina', 'huevos', 'leche', 'polvo-hornear', 'dulce-de-leche'], opt: ['banana', 'crema', 'manteca'] },
  { id: 'tostadas-mermelada', name: 'Tostadas con mermelada', section: 'dulce', tags: ['clasico'],
    desc: 'Pan tostado · mermelada a elección',
    need: [['pan', 'pan-lactal'], 'mermelada'], opt: ['manteca'] },
  { id: 'tostadas-francesas', name: 'Tostadas francesas', section: 'dulce', tags: ['casa'],
    desc: 'Pan pasado por huevo y leche · dorado en manteca · azúcar y canela',
    need: [['pan', 'pan-lactal'], 'huevos', 'leche', 'azucar', 'manteca'], opt: ['canela', 'miel', 'dulce-de-leche', 'frutilla'] },
  { id: 'banana-ddl', name: 'Banana con dulce de leche', section: 'dulce', tags: ['rapido'],
    desc: 'Banana en rodajas · dulce de leche encima',
    need: ['banana', 'dulce-de-leche'], opt: ['nueces', 'crema', 'chocolate'] },
  { id: 'fruta', name: 'Fruta', section: 'dulce', tags: ['veggie'],
    desc: 'Fruta fresca de temporada',
    need: [['fruta-estacion', 'banana', 'manzana', 'frutilla', 'naranja']], opt: ['miel', 'yogur'] },
  { id: 'galletitas', name: 'Galletitas', section: 'dulce', tags: ['rapido'],
    desc: 'Surtido · preguntar disponibilidad',
    need: ['galletitas'] },
  { id: 'alfajor', name: 'Alfajor', section: 'dulce', tags: ['clasico'],
    desc: 'De la reserva secreta',
    need: ['alfajores'] },
  { id: 'helado', name: 'Helado', section: 'dulce', tags: ['estrella'],
    desc: 'Bocha o pote · dulce de leche encima opcional',
    need: ['helado'], opt: ['dulce-de-leche', 'chocolate', 'nueces', 'banana'] },
  { id: 'chocolatada', name: 'Chocolatada', section: 'dulce', tags: ['suave'],
    desc: 'Leche · cacao · azúcar · fría o caliente',
    need: ['leche', 'cacao', 'azucar'], opt: ['hielo', 'canela'] },
  { id: 'mug-cake', name: 'Mug cake de chocolate', section: 'dulce', tags: ['casa'],
    desc: 'Bizcochuelo en taza · 90 segundos al microondas',
    need: ['harina', 'cacao', 'azucar', 'leche', 'aceite'], opt: ['huevos', 'polvo-hornear', 'chocolate', 'helado'] },
  { id: 'manzana-canela', name: 'Manzana con canela', section: 'dulce', tags: ['veggie'],
    desc: 'Manzana salteada en manteca · canela · azúcar',
    need: ['manzana', 'canela', 'azucar'], opt: ['manteca', 'miel', 'nueces', 'helado'] },
];
